config/routes.rb
Rails.application.routes.draw do
  get 'upvotes/create'

  get 'upvotes/destroy'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "subjects#index"
  resources :subjects do
    resources :messages
    resources :upvotes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  validates :content, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true

  def score
    upvotes.count
  end
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :subject
  belongs_to :user

  validates :subject, uniqueness: { scope: :user }
  validates :user, uniqueness: { scope: :subject }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_subject, only: [:new, :create, :edit, :update, :show, :destroy]
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.subject = @subject
    if @message.save
      respond_to do |format|
        format.js
        format.html { redirect_to subject_path(@subject) }
      end
    else
      respond_to do |format|
        format.js
        format.html { render 'subject/show' }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    @message.update(message_params)
    redirect_to subject_path(@subject)
  end

  def destroy
    if @message.destroy
      respond_to do |format|
        format.js
        format.html { redirect_to subject_path(@subject) }
      end
    else
      respond_to do |format|
        format.js
        format.html { render 'subject/show' }
      end
    end
  end

  private
  def set_message
    @message = Message.find(params[:id])
  end

  def set_subject
    @subject = Subject.find(params[:subject_id])
  end

  def message_params
    params.require(:message).permit(:content, :subject_id, :user_id)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :update, :edit, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def new
    @subject = Subject.new
  end

  def index
    @subjects = Subject.all.sort {|a,b| b.score <=> a.score}
  end

  def show
    @message = Message.new
    @messages = Message.where(subject_id: @subject)
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.user = current_user
    if @subject.save
      redirect_to subjects_path
    else
      redirect_to new_subject_path
    end
  end

  def edit
  end

  def update
    @subject.update(subject_params)
    redirect_to subjects_path
  end

  def destroy
    @subject.destroy
    redirect_to subjects_path
  end

  private

  def subject_params
    params.require(:subject).permit(:title, :content, :user_id)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    @upvote = Upvote.new(upvote_params)
    @upvote.subject = Subject.find(params[:subject_id])
    if @upvote.save
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
  end

  private
  def upvote_params
    params.require(:upvote).permit(:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-reddit">
  <div class="navbar-logo">
    <%= link_to root_path do %>
      <%= image_tag("reddit-logo.png") %>
    <% end %>
  </div>
  <div class="navbar-right">
    <div class="navbar-links">
      <% if user_signed_in? %>
        <%= link_to "New subject", new_subject_path, class: "navbar-link" %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn-navbar" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn-navbar"  %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn-navbar" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_new.html.erb
<div id="new_message">
  <%= simple_form_for [@subject, @message], remote: true do |f| %>
    <%= f.error_notification %>

    <%= f.input :content, label: 'Content', as: :text %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/messages/_show.html.erb
<div class="message">
  <p><%= message.content %></p>
  <div class="message-autor">
    <p style="display: inline-block;"><%= message.user.username %></p>
    <% if message.user_id == current_user.id %>
      <%= link_to edit_subject_message_path(@subject,message) do %>
        <i style="display: inline-block;" class="fa fa-pencil"></i>
      <% end %>
      <%= link_to subject_message_path(@subject, message), method: :delete, remote: true do %>
        <i style="display: inline-block;" class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/messages/create.js.erb
<% if @message.errors.any? %>
  // Render new message form with errors
  $('#new_message').html("<%= j render 'subjects/show', subject: @subject %>");
<% else %>
  // Create a paragraph for the new message. But hide it.
  var new_message = $("<%= j render 'messages/show', message: @message %>").hide();
  // Add it to the DOM, at the end of the existing messages. It's still hidden.
  $('#messages').append(new_message);
  // Show the new message with an animation!
  new_message.slideDown();
<% end %>

app/views/messages/destroy.js.erb
$("#message_<%= @message.id %>").fadeOut();

app/views/messages/edit.html.erb
<div class="container">
  <h1>Edit Message</h1>
  <%= simple_form_for [@subject, @message] do |f| %>
    <%= f.error_notification %>

    <%= f.input :content, label: "Content", as: :text %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<div class="container">
  <h1>Edit subject</h1>
  <%= simple_form_for [@subject] do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, label: "Title" %>
    <%= f.input :content, label: "Content", as: :text %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="container">
  <h1>List of subjects</h1>
  <div class="subjects">

    <% @subjects.each do |subject| %>
      <ul>
        <li>
          <div class="subject">
            <div class="subject-header">
              <div class="subject-title">
                <%= link_to subject_path(subject) do %>
                  <h4><%= subject.title %></h4>
                <% end %><p style="display: inline-block;">Votes: <%= subject.score %></p>
                <% if user_signed_in? && subject.user_id == current_user.id %>
                  <%= link_to edit_subject_path(subject) do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to subject_path(subject), method: :delete do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="subject-author">
                <p>Started by <%= subject.user.username %></p>
              </div>
            </div>
            <div class="subject-body">
              <p><%= subject.content.truncate(50) %></p>
            </div>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="container">
<h1>What's on your mind ?</h1>
  <%= simple_form_for [@subject] do |f|  %>
    <%= f.error_notification %>

    <%= f.input :title, label: "Title" %>
    <%= f.input :content, label: "Content" %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/subjects/show.html.erb
<div class="container">
  <div class="subject-show">
    <div class="subject-header">
      <div class="subject-title">
        <h4 style="display: inline-block;"><%= @subject.title %></h4>
        <p style="display: inline-block;">Votes: <%= @subject.score %></p>
        <% if user_signed_in? && @subject.user_id == current_user.id %>
          <%= link_to edit_subject_path(@subject) do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        <% end %>
      </div>
      <div class="subject-author">
        <p>Started by <%= @subject.user.username %></p>
      </div>
    </div>
    <div class="subject-body">
      <div class="subject-content">
        <p><%= @subject.content %></p>
      </div>
      <div class="subject-vote">
        <%= simple_form_for @subject.upvotes.build, url: subject_upvotes_path(@subject), remote: true do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit '+1', class: 'button upvote-submit' %>
        <% end %>
      </div>
      <div id="messages">
        <% if @messages %>
          <% @messages.each do |message| %>
            <div id="message_<%= message.id %>">
              <%= render 'messages/show', subject: @subject, message: message %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="add-message">
    <%= render 'messages/new', subject: @subject, message: @message %>
  </div>
  <div class="nav-buttons">
    <%= link_to "Back", subjects_path, class: 'button' %>
  </div>
</div>

app/views/upvotes/_create.js.erb
$(document).ready(function() {
  console.log('redstar')
  $('.upvote-submit').css('color', 'orange');
});

app/views/upvotes/create.html.erb
<h1>Upvotes#create</h1>
<p>Find me in app/views/upvotes/create.html.erb</p>

app/views/upvotes/destroy.html.erb
<h1>Upvotes#destroy</h1>
<p>Find me in app/views/upvotes/destroy.html.erb</p>